### PR TITLE
Add Scalene CPU+mem profiling

### LINKED ISSUE #1: Add Internal Benchmark tooling
To facilitate tracking of benchmarks internal to the job runs the MAAP team is recommending Scalene for python code.

- [x] Wrap existing algorithm in Scalene

### PR DESCRIPTION
**Pull request by chuckwondo**
Here's what I did:

- Added the [Scalene](https://github.com/plasma-umass/scalene) profiler to this algorithm so that we can see how memory and CPU are used, beyond calls to `time` within the code. This produces a profiling report named `profile.html` in the algorithm's output directory.
- Refactored for a bit of clarity and to address a few issues that were noted in code comments. Everything now works cleanly and consistently in both the ADE and DPS.
- Added `algorithm_config.yml` to the repo to enable programmatic algorithm registration. Note that prior to each release, the value of `algorithm_version` should be changed appropriately, in sync with changing `get_dem.__version__` as well, prior to registration, in order for a new version to be registered. Registration should likely occur _after_ merging the bumped versions into `develop` and tagging `develop` with the version value as well.

Fixes #1

### CODE REVIEW

**Comment by chuckwondo** [comment]
BTW, I registered `GET-DEM:scalene` to test the changes, so if you want to give things a spin, choose that algo.

**Comment by chuckwondo** [comment]
@nemo794, although the total amount of code is small, I made significant changes, so I'd be happy to pair up with you to go over them, if you like.

**Comment by nemo794** [comment]
Hi @chuckwondo , That'd be great.

**Comment by chuckwondo** [comment]
@nemo794, I've sent you a DM in the Slack ESA-NASA MAAP workspace regarding my availability.

**Comment by chuckwondo** [comment]
Closing this PR after @nemo794 and I discussed the need to break it into smaller pieces, and also the need to wait for other PRs to land first, in order to support better coordination between NASA and ESA.

**Comment by wildintellect** [comment]
@chuckwondo can you be more specific, are you waiting for #2 to happen first?

**Comment by chuckwondo** [comment]
Sorry, yes, waiting for #2 to happen first. Also, @nemo794 and I discovered that the call out to `sardem` via a system call does not allow scalene to capture profiling details, so I'll work on changing get-dem to call `sardem` directly via a function call, which should allow us to get a complete profiling report.

Once #2 lands, Sam and I will work on creating a small, focused PR to get `scalene` integrated with as few changes as possible, hopefully making it easier for ESA to pull in as well.

**Pull request closed without merging**
