### PR TITLE
ESA application package wrapper

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nemo794** [comment]
This is so neat! Adding @sujen1412 and @wildintellect as reviewers, mostly for awareness for the platform and data teams (respectively), so they can look deeper into the ESA interface if desired.

**Comment by sujen1412** [comment]
This looks good, @nemo794 we should commit our algorithm yaml under nasa dir to this repo as well.

**Review by sujen1412 — APPROVED** [review]

**Review by wildintellect — APPROVED** [review]

**Comment by nemo794** [comment]
Hi @arthurduf , As a general question, it looks like the two modules in [esa/driver/maap_utils/](https://github.com/MAAP-Project/get-dem/pull/5/files#diff-cd2609e7ae451211cc461d06197360618950c3a3733dac85f9f46e03a674d416) are generic for the ESA MAAP platform, and are not specialized for the running this algorithm. Is that a correct understanding? If so, were these only copied to the `get-dem` repo for ease in this use case, or does each ESA MAAP user need to make a copy into their own repo?

**Comment by ghost** [comment]
Hi @nemo794 
You understood correctly, the two modules in esa/driver/maap_utils are only used in the "driver notebook" to authenticate and launch  WPS-T version of get-dem. 
For now it is just a prototype that each user has to copy, but we are working on a more "complete and industrial version" that will be embedded in the ADE stack as a conda package.

**Review by nemo794 — APPROVED** [review]
LGTM! Thank you for adding this, and for clarifying the `../esa/driver/maap_utils/*` files.

**Comment by ghost** [comment]
Can somebody (@sujen1412 maybe ?)  show me how the Docker image is produce in NASA env ? I am trying to figure out how to build an Application Package from the "nasa" folder with the ESA generator

**Comment by nemo794** [comment]
Hi @arthurduf , When you're ready, could you please merge this branch? I think all comments were addressed, but if I missed something, please let me know. Thank you!

**Comment by ghost** [comment]
Hi @nemo794 , so sorry I was just waiting for an admin ( or someone else) to merge it....

**Pull request merged**
