### PR TITLE
Use pseudo-inverse computation

### LINKED ISSUE #7: Some bbox inputs raise numpy.linalg.LinAlgError: Singular matrix
The `do_computations` function attempts to compute the multiplicative inverse of a square matrix. When the matrix is not invertible (i.e., its determinant is 0), the following error is raised: `numpy.linalg.LinAlgError: Singular matrix`

The fix for this is to simply compute the pseudo-inverse, which does not require the matrix to be invertible.

### PR DESCRIPTION
**Pull request by chuckwondo**
Use `numpy.linalg.pinv` instead of `numpy.linalg.inv` to avoid "singular matrix" errors.

Upgrade `numpy` in `Dockerfile` to avoid "hanging" during computation of pseudo-inverse.

Fixes #7

### CODE REVIEW

**Comment by chuckwondo** [comment]
@arthurduf, please take a look at this. I suggest pulling the branch and testing.

**Comment by ghost** [comment]
All good for me

**Review by ghost — APPROVED** [review]

**Comment by nemo794** [comment]
Just a heads up that `numpy.linalg.pinv` takes a significantly longer to run than `numpy.linalg.inv`. (That said, I confirmed via `htop` that `pinv` does use all available cores, so we're good there.)

Is this what we want?

```
>>> import timeit
>>> inv = '''\
... import numpy as np
... pos = np.random.randint(0, 10, size=(5000,5000))
... np.linalg.inv(pos)
... '''
>>> pinv = '''\
... import numpy as np
... pos = np.random.randint(0, 10, size=(5000,5000))
... np.linalg.pinv(pos)
... '''
>>> timeit.timeit(inv, number=1)
4.161739458999364
>>> timeit.timeit(pinv, number=1)
43.71366904099705
```

**Comment by chuckwondo** [comment]
> Just a heads up that `numpy.linalg.pinv` takes a significantly longer to run than `numpy.linalg.inv`. (That said, I confirmed via `htop` that `pinv` does use all available cores, so we're good there.)
> 
> Is this what we want?
> 
> ```
> >>> import timeit
> >>> inv = '''\
> ... import numpy as np
> ... pos = np.random.randint(0, 10, size=(5000,5000))
> ... np.linalg.inv(pos)
> ... '''
> >>> pinv = '''\
> ... import numpy as np
> ... pos = np.random.randint(0, 10, size=(5000,5000))
> ... np.linalg.pinv(pos)
> ... '''
> >>> timeit.timeit(inv, number=1)
> 4.161739458999364
> >>> timeit.timeit(pinv, number=1)
> 43.71366904099705
> ```

Generally speaking, as long as this has the intended effect of consuming resources, I'd say this is fine. The actual computation is not what we care about, is it? Unless this particular calculation is going to cause the larger bboxes to take _inordinately_ long (hours?) to complete, this should be fine, no?

**Pull request merged**
